twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['tailwind_2_layout.html.twig']
#    form_themes: ['bootstrap_4_layout.html.twig']
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
